### ISSUE TITLE
hackage release

### ISSUE THREAD

**Issue by funketh** [metrix-ai/primitive-extras#4]
could we get a new hackage release for v0.14.1?

**Comment by nikita-volkov** [comment]
Versions above 0.10 have been highly experimental, hence not publicly released. There's also been a bit of confusion where I kept that development in the master branch. Now I've reassigned master to the developments based on 0.10 and moved the experimental stuff to "dev". 0.10 is the main supported version for now. I have updated the bounds in it and released.
