### ISSUE TITLE
spock build fails on primitive-extras

### ISSUE THREAD

**Issue by aleeusgr** [metrix-ai/primitive-extras#7]
I am building a REST endpoint using [Spock](https://hackage.haskell.org/package/Spock); 
Following this tutorial with [minor tweaks](https://github.com/agrafix/Spock/issues/182) I get this error upon
`stack build`:

>-- While building package primitive-extras-0.8 (scroll up to its section to see the error) using:
primitive-extras > Ambiguous occurrence ‘singleton’ primitive-extras > It could refer to
primitive-extras > either ‘PrimitiveExtras.Prelude.singleton’,
primitive-extras > imported from ‘PrimitiveExtras.Prelude’ at library/PrimitiveExtras/Bitmap.
hs:25:1-70
primitive-extras > (and originally defined in ‘base-4.15.1.0:Data.OldList’)
primitive-extras > or ‘PrimitiveExtras.Bitmap.singleton’,
primitive-extras > defined at library/PrimitiveExtras/Bitmap.hs:53:1
primitive-extras > |
primitive-extras > 5 | singleton,
primitive-extras > | ^^^^^^^^^

can you help me fix this?
thank you

my system is Linux nixos 5.15.70
stack --version: 2.7.5 x86_64 hpack-0.34.7
The Glorious Glasgow Haskell Compilation System, version 9.0.2
[More info](https://github.com/SIDANWhatever/plutus-cborhex-automation/issues/16)

**Comment by nikita-volkov** [comment]
I sense you're referring to [this tutorial](https://www.spock.li/tutorials/getting-started). It suggests to explicitly specify an outdated version of this package as well as others. Instead just use the latest nightly or LTS snapshot in stack, which will automatically bring the correct dependencies in.

**Comment by aleeusgr** [comment]
Thank you!
It would seem you are right: I cloned a hello-project and used `resolver: lts-19.28`, but still Spock would not build. Keep digging.
